##   此配置文件为server公用配置文件，私有配置信息已注释
##   此配置文件为server公用配置文件，私有配置信息已注释
spring:
#  application:
#    name: system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=UTF8&autoReconnect=true&useSSL=false
    username: user_demo
    password: 123456

#server:
#  port: 9001
#  servlet:
#    context-path: /system
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/


mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.huanghao.server.mapper: trace


